# -*- coding: utf-8 -*-
"""blp_visualizer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_85V0U5yVSQBcwyNcr5y3jwdyITrw_GU
"""

# ==============================
# BLP MODEL (CORE LOGIC)
# ==============================

class Subject:
    def __init__(self, name, max_level, current_level):
        self.name = name
        self.max_level = max_level
        self.current_level = current_level


class Object:
    def __init__(self, name, level):
        self.name = name
        self.level = level


class BLPModel:
    def __init__(self):
        self.levels = {"U": 0, "C": 1, "S": 2, "TS": 3}
        self.subjects = {}
        self.objects = {}

    def add_subject(self, name, max_level, start_level):
        if self.levels[start_level] > self.levels[max_level]:
            print("Invalid subject levels")
            return False
        self.subjects[name] = Subject(name, max_level, start_level)
        return True

    def add_object(self, name, level):
        self.objects[name] = Object(name, level)

    def set_level(self, subject_name, new_level):
        subject = self.subjects[subject_name]

        if self.levels[new_level] > self.levels[subject.max_level]:
            print(f"{subject_name} cannot exceed max level")
            return False

        if self.levels[new_level] < self.levels[subject.current_level]:
            print(f"{subject_name} cannot lower level")
            return False

        subject.current_level = new_level
        print(f"{subject_name} level set to {new_level}")
        return True

    def read(self, subject_name, object_name):
        subject = self.subjects[subject_name]
        obj = self.objects[object_name]

        print(f"{subject_name} attempts to READ {object_name}")

        if self.levels[obj.level] > self.levels[subject.current_level]:
            if self.levels[obj.level] <= self.levels[subject.max_level]:
                subject.current_level = obj.level
                print(f"Level upgraded to {obj.level} -> READ allowed")
            else:
                print("READ denied (No Read Up)")
                return

        else:
            print("READ allowed")

    def write(self, subject_name, object_name):
        subject = self.subjects[subject_name]
        obj = self.objects[object_name]

        print(f"{subject_name} attempts to WRITE {object_name}")

        if self.levels[subject.current_level] > self.levels[obj.level]:
            print("WRITE denied (No Write Down)")
        else:
            print("WRITE allowed")

    def show_state(self):
        print("\n--- CURRENT LEVELS ---")
        print(f"Alice: {self.subjects['Alice'].current_level}")
        print(f"Bob: {self.subjects['Bob'].current_level}")
        print(f"Eve: {self.subjects['Eve'].current_level}")
        print("----------------------\n")

# ==============================
# SETUP + TEST CASES
# ==============================

def setup_system():
    blp = BLPModel()

    blp.add_subject("Alice", "S", "U")
    blp.add_subject("Bob", "C", "C")
    blp.add_subject("Eve", "U", "U")

    blp.add_object("pub.txt", "U")
    blp.add_object("emails.txt", "C")
    blp.add_object("username.txt", "S")
    blp.add_object("password.txt", "TS")

    return blp



# CASE 1
blp = setup_system()
print("========== CASE 1 ==========")
blp.read("Alice", "emails.txt")
blp.show_state()


# CASE 2
blp = setup_system()
print("========== CASE 2 ==========")
blp.read("Alice", "password.txt")
blp.show_state()


# CASE 3
blp = setup_system()
print("========== CASE 3 ==========")
blp.read("Eve", "pub.txt")
blp.show_state()


# CASE 4
blp = setup_system()
print("========== CASE 4 ==========")
blp.read("Eve", "emails.txt")
blp.show_state()


# CASE 5
blp = setup_system()
print("========== CASE 5 ==========")
blp.read("Bob", "password.txt")
blp.show_state()


# CASE 6
blp = setup_system()
print("========== CASE 6 ==========")
blp.read("Alice", "emails.txt")
blp.write("Alice", "pub.txt")
blp.show_state()


# CASE 7
blp = setup_system()
print("========== CASE 7 ==========")
blp.read("Alice", "emails.txt")
blp.write("Alice", "password.txt")
blp.show_state()


# CASE 8
blp = setup_system()
print("========== CASE 8 ==========")
blp.read("Alice", "emails.txt")
blp.write("Alice", "emails.txt")
blp.read("Alice", "username.txt")
blp.write("Alice", "emails.txt")
blp.show_state()


# CASE 9
blp = setup_system()
print("========== CASE 9 ==========")
blp.read("Alice", "username.txt")
blp.write("Alice", "emails.txt")
blp.read("Alice", "password.txt")
blp.write("Alice", "password.txt")
blp.show_state()


# CASE 10
blp = setup_system()
print("========== CASE 10 ==========")
blp.read("Alice", "pub.txt")
blp.write("Alice", "emails.txt")
blp.read("Bob", "emails.txt")
blp.show_state()


# CASE 11
blp = setup_system()
print("========== CASE 11 ==========")
blp.read("Alice", "pub.txt")
blp.write("Alice", "username.txt")
blp.read("Bob", "username.txt")
blp.show_state()


# CASE 12
blp = setup_system()
print("========== CASE 12 ==========")
blp.read("Alice", "pub.txt")
blp.write("Alice", "password.txt")
blp.read("Bob", "password.txt")
blp.show_state()


# CASE 13
blp = setup_system()
print("========== CASE 13 ==========")
blp.read("Alice", "pub.txt")
blp.write("Alice", "emails.txt")
blp.read("Eve", "emails.txt")
blp.show_state()


# CASE 14
blp = setup_system()
print("========== CASE 14 ==========")
blp.read("Alice", "emails.txt")
blp.write("Alice", "pub.txt")
blp.read("Eve", "pub.txt")
blp.show_state()


# CASE 15
blp = setup_system()
print("========== CASE 15 ==========")
blp.set_level("Alice", "S")
blp.read("Alice", "username.txt")
blp.show_state()


# CASE 16
blp = setup_system()
print("========== CASE 16 ==========")
blp.read("Alice", "emails.txt")
blp.set_level("Alice", "U")
blp.write("Alice", "pub.txt")
blp.read("Eve", "pub.txt")
blp.show_state()


# CASE 17
blp = setup_system()
print("========== CASE 17 ==========")
blp.read("Alice", "username.txt")
blp.set_level("Alice", "C")
blp.write("Alice", "emails.txt")
blp.read("Eve", "emails.txt")
blp.show_state()


# CASE 18
blp = setup_system()
print("========== CASE 18 ==========")
blp.read("Eve", "pub.txt")
blp.read("Eve", "emails.txt")
blp.show_state()